"""New Migration

Revision ID: 6196527b46f0
Revises: 
Create Date: 2023-07-27 17:04:38.056515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6196527b46f0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "todos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("todos")
    # ### end Alembic commands ###
